#define TRUE				1
#define FALSE				0

#define SANT				TRUE
#define FALSKT				FALSE

#define sjalvbestammande	auto
#define bryt				break
#define fall				case
#define tecken				char
#define kostant				const
#define fortsatt			continue
#define standard			default
#define gor					do
#define dubbel				double
#define annars				else
#define raknare				enum
#define utifran				extern
#define flyttal				float
#define varje				for
#define gatill				goto
#define om					if
#define hel					int
#define lang				long
#define registrera			register
#define skickatillbaks		return
#define kort				short
#define signerad			signed
#define storlekav			sizeof
#define statisk				static
#define struktur			struct
#define byt					switch
#define typdefinition		typedef
#define sammansattning		union
#define osignerad			unsigned
#define tomrum				void
#define flyktig				volatile
#define medan				while 

#define skrivf				printf
#define lasf				scanf
